### ISSUE TITLE
App not starting after pygame update

### ISSUE THREAD

**Issue by claytonrfe** [vicwomg/pikaraoke#121]
I installed pikraoke manually on my RetroPie (RPi 4B) and had it working, but no videos were playing when a song started. After some online searches, saw a recommendation of re-installing pygame. I did it and now the app does not open anymore.

pi@retropie:/home/pikaraoke $ sudo python3 app.py
pygame 2.0.1 (SDL 2.0.10, Python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
[2021-05-20 17:47:55] INFO: VLC command base: /usr/bin/vlc -f --play-and-exit --extraintf http --http-port 5002 --http-password oHDxNGFjWEEDkbVSFTrJ4dnM3gQ0yUsa --no-embedded-video --no-keyboard-events --no-mouse-events --mouse-hide-timeout 0 --video-on-top --no-video-title --mouse-hide-timeout 0
Traceback (most recent call last):
  File "app.py", line 801, in <module>
    show_overlay=args.show_overlay
  File "/home/pikaraoke/karaoke.py", line 179, in __init__
    self.render_splash_screen()
  File "/home/pikaraoke/karaoke.py", line 316, in render_splash_screen
    logo = pygame.image.load(self.logo_path)
pygame.error: File is not a Windows BMP file
pi@retropie:/home/pikaraoke $

**Comment by vicwomg** [comment]
yes, pygame is very particular concerning versions. You can try uninstalling the version you updated with `sudo pip3 pygame`, then re-run `./setup-pi.sh`

As for videos not playing, that sounds like more of the bug here. If you get back to that point, can you file a new ticket with what you're experiencing and any relevant log output?

**Comment by claytonrfe** [comment]
Sure. Thank you, downgrading pygame did fix the startup issue, but now back to the no video issue. I will open a separate ticket.
