### ISSUE TITLE
XDG_RUNTIME_DIR error on VLC when playing videos

### ISSUE THREAD

**Issue by troy-lim** [vicwomg/pikaraoke#188]
Output of pikaraoke.log:

[2022-01-30 02:03:17] INFO: Fetching available songs in: /root/pikaraoke-songs/
[2022-01-30 02:03:18] INFO: VLC command base: /usr/bin/vlc -f --play-and-exit --extraintf http --http-port 5002 --http-password kuIo8Z1FWRj6Jjp5g1EDHNVb5eBVccoK --no-embedded-video --no-keyboard-events --no-mouse-events --mouse-hide-timeout 0 --video-on-top --no-video-title --mouse-hide-timeout 0
[30/Jan/2022:02:03:18] ENGINE Bus STARTING
[2022-01-30 02:03:18] INFO: [30/Jan/2022:02:03:18] ENGINE Bus STARTING
[30/Jan/2022:02:03:18] ENGINE Started monitor thread '_TimeoutMonitor'.
[2022-01-30 02:03:18] INFO: [30/Jan/2022:02:03:18] ENGINE Started monitor thread '_TimeoutMonitor'.
[30/Jan/2022:02:03:18] ENGINE Serving on http://0.0.0.0:5000
[2022-01-30 02:03:18] INFO: [30/Jan/2022:02:03:18] ENGINE Serving on http://0.0.0.0:5000
[30/Jan/2022:02:03:18] ENGINE Bus STARTED
[2022-01-30 02:03:18] INFO: [30/Jan/2022:02:03:18] ENGINE Bus STARTED
[2022-01-30 02:03:18] INFO: Starting PiKaraoke!
[2022-01-30 02:03:33] INFO: 'Chewbacca' is adding song to queue: /root/pikaraoke-songs/A-ha - The Sun Always Shines On T.V. - Karaoke Version from Zoom Karaoke---_XVjhOHZuiY.mp4
[2022-01-30 02:03:39] INFO: Playing video in VLC: A-ha - The Sun Always Shines On T.V. - Karaoke Version from Zoom Karaoke
[00005619f604f480] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
[00005619f60e7930] dbus interface error: Failed to connect to the D-Bus session daemon: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
[00005619f60e7930] main interface error: no suitable interface module
[00005619f5fae570] main libvlc error: interface "dbus,none" initialization failed
[00005619f60e7930] [http] lua interface: Lua HTTP interface
[00005619f607d8f0] main interface error: no suitable interface module
[00005619f5fae570] main libvlc error: interface "globalhotkeys,none" initialization failed
[00005619f5fae570] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
error: XDG_RUNTIME_DIR not set in the environment.
[00005619f607d8f0] skins2 interface error: cannot initialize OSFactory
[00005619f607d8f0] [cli] lua interface: Listening on host "*console".
VLC media player 3.0.12 Vetinari
Command Line Interface initialized. Type `help' for help.
> error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
[00007f3a74001370] gl vout display error: parent window not available
[00007f3a74001370] gles2 vout display error: parent window not available
[00007f3a74001370] xcb vout display error: window not available

[2022-01-30 02:03:53] INFO: Clearing queue!
[2022-01-30 02:03:53] WARNING: Tried to skip, but no file is playing!
[30/Jan/2022:02:03:53] ENGINE Bus STOPPING
[2022-01-30 02:03:53] INFO: [30/Jan/2022:02:03:53] ENGINE Bus STOPPING
[30/Jan/2022:02:03:53] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 5000)) shut down
[2022-01-30 02:03:53] INFO: [30/Jan/2022:02:03:53] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 5000)) shut down
[30/Jan/2022:02:03:53] ENGINE Stopped thread '_TimeoutMonitor'.
[2022-01-30 02:03:53] INFO: [30/Jan/2022:02:03:53] ENGINE Stopped thread '_TimeoutMonitor'.
[30/Jan/2022:02:03:53] ENGINE Bus STOPPED
[2022-01-30 02:03:53] INFO: [30/Jan/2022:02:03:53] ENGINE Bus STOPPED
[30/Jan/2022:02:03:53] ENGINE Bus STOPPING
[2022-01-30 02:03:53] INFO: [30/Jan/2022:02:03:53] ENGINE Bus STOPPING
[30/Jan/2022:02:03:53] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 5000)) already shut down
[2022-01-30 02:03:53] INFO: [30/Jan/2022:02:03:53] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 5000)) already shut down
[30/Jan/2022:02:03:53] ENGINE No thread running for None.
[2022-01-30 02:03:53] INFO: [30/Jan/2022:02:03:53] ENGINE No thread running for None.
[30/Jan/2022:02:03:53] ENGINE Bus STOPPED
[2022-01-30 02:03:53] INFO: [30/Jan/2022:02:03:53] ENGINE Bus STOPPED
[30/Jan/2022:02:03:53] ENGINE Bus EXITING
[2022-01-30 02:03:53] INFO: [30/Jan/2022:02:03:53] ENGINE Bus EXITING
[30/Jan/2022:02:03:53] ENGINE Bus EXITED
[2022-01-30 02:03:53] INFO: [30/Jan/2022:02:03:53] ENGINE Bus EXITED
[30/Jan/2022:02:03:54] ENGINE Bus STOPPING
[2022-01-30 02:03:54] INFO: [30/Jan/2022:02:03:54] ENGINE Bus STOPPING
[30/Jan/2022:02:03:54] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 5000)) already shut down
[2022-01-30 02:03:54] INFO: [30/Jan/2022:02:03:54] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 5000)) already shut down
[30/Jan/2022:02:03:54] ENGINE No thread running for None.
[2022-01-30 02:03:54] INFO: [30/Jan/2022:02:03:54] ENGINE No thread running for None.
[30/Jan/2022:02:03:54] ENGINE Bus STOPPED
[2022-01-30 02:03:54] INFO: [30/Jan/2022:02:03:54] ENGINE Bus STOPPED
[30/Jan/2022:02:03:54] ENGINE Bus EXITING
[2022-01-30 02:03:54] INFO: [30/Jan/2022:02:03:54] ENGINE Bus EXITING
[30/Jan/2022:02:03:54] ENGINE Bus EXITED
[2022-01-30 02:03:54] INFO: [30/Jan/2022:02:03:54] ENGINE Bus EXITED
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html

But, if I run 
/usr/bin/vlc -f /home/pi/pikaraoke-songs/filename.mp4
The video plays.

(Yes, my username is pi eventhough it's installed on an x86 machine :))
I also created a symlink of /root/pikaraoke-songs to /home/pi/pikaraoke-songs and made the directories accessible.

**Comment by Hartebee5t** [comment]
I've encountered what I believe to be similar errors running on a RPi4 (specifically the "vlcpulse audio output error" and the dbus interface error following it in your log). 
I've not yet found a cause or workaround but I noticed that if I launch the pikaraoke app from power-up (using \etc\rc.local) it usually works, but if I quit back to the pi desktop and re-run from the CLI in a shell window, with exactly the same command that worked from rc.local, the app runs and videos play but there's no sound. At that point, if I run VLC directly the videos play with audio working fine.
It's as if there's an explicit audio option or parameter missing from the vlc command within the app, similar in purpose to the -a option provided for omxplayer. It defaults correctly from rc.local launch of the pikaraoke app, and from direct VLC launch from desktop, but defaults to some other audio when pikaraoke gets re-launched after quitting.
Apologies if this turns out to be a different issue, but there seem to be enough parallels to make it relevant.

**Comment by troy-lim** [comment]
In my case, if I run "/usr/bin/vlc -f /home/pi/pikaraoke-songs/filename.mp4" the video plays without any problem but after the video is done playing I see something like this:

VLC media player 3.0.12 Vetinari (revision 3.0.12-1-0-gd147bb5e7e)
[00005594927d6f10] main interface error: no suitable interface module
[00005594926f2570] main libvlc error: interface "globalhotkeys,none" initialization failed
[00005594926f2570] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[00005594927d6f10] skins2 interface error: cannot initialize OSFactory
[00005594927d6f10] [cli] lua interface: Listening on host "*console".
VLC media player 3.0.12 Vetinari
Command Line Interface initialized. Type `help' for help.
[00007f218c001370] gl vout display error: parent window not available
[00007f218c001370] gles2 vout display error: parent window not available
[00007f218c001370] xcb vout display error: window not available

Then I have to type ctrl+C to terminate vlc.

Gong back to PiKaraoke, if I run "sudo python3 app.py", the web interface is working as it should. Search and download is working, also queueing. But after queue, the song shows up in the Home tab but only for a few seconds as if it played and finished the song.

**Comment by vicwomg** [comment]
Just to be clear, you're running on linux? Have you tried without running `python3 app.py` without sudo?

**Comment by troy-lim** [comment]
> Just to be clear, you're running on linux? 

Yes. Debian Buster on an Intel atom.

**Comment by troy-lim** [comment]
> Have you tried without running `python3 app.py` without sudo?

![IMG20220201064326.jpg](https://user-images.githubusercontent.com/73457175/151885425-81aa4a6e-8a19-42b3-acfa-d97445a2768c.jpg)

**Comment by vicwomg** [comment]
this is probably because you ran once as sudo and it generated the qrcode with root permissions. If you `sudo rm /home/pi/pikaraoke/qrcode.png` then try again you should get further

**Comment by troy-lim** [comment]
> Have you tried without running `python3 app.py` without sudo?

pi@happykaraoke:~/pikaraoke$ python3 app.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contrib
ute.html
[2022-02-01 06:48:01] INFO: Fetching available songs in: /home/
pi/pikaraoke-songs/
Traceback (most recent call last):
  File "app.py", line 816, in <module>
    show_overlay=args.show_overlay
  File "/home/pi/pikaraoke/karaoke.py", line 173, in __init__
    self.generate_qr_code()
  File "/home/pi/pikaraoke/karaoke.py", line 267, in generate_q
r_code
    img.save(self.qr_code_path)
  File "/usr/local/lib/python3.7/dist-packages/qrcode/image/pil
.py", line 58, in save
    self._img.save(stream, format=format, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", l
ine 2209, in save
    fp = builtins.open(filename, "w+b")
PermissionError: [Errno 13] Permission denied: '/home/pi/pikara
oke/qrcode.png'
pi@happykaraoke:~/pikaraoke$

**Comment by troy-lim** [comment]
> Have you tried without running `python3 app.py` without sudo?

![IMG20220201064326.jpg](https://user-images.githubusercontent.com/73457175/151886657-699c729b-7800-45d6-a469-7c11156c0bc0.jpg)

**Comment by troy-lim** [comment]
> this is probably because you ran once as sudo and it generated the qrcode with root permissions. If you `sudo rm /home/pi/pikaraoke/qrcode.png` then try again you should get further

It says unable to open mouse.

![IMG20220201072341.jpg](https://user-images.githubusercontent.com/73457175/151889640-1d480865-b7a3-4107-b576-5ed19d67fca6.jpg)

**Comment by vicwomg** [comment]
Ok, back to sudo then, pygame is being restrictive... especially when running in a non-desktop environment, which sounds familiar. Did you try patching vlc so that it can run as sudo? As it turns out, this is a necessary step in the pi installations:

`sed -i 's/geteuid/getppid/' /usr/bin/vlc `

**Comment by troy-lim** [comment]
> Ok, back to sudo then, pygame is being restrictive... especially when running in a non-desktop environment, which sounds familiar. Did you try patching vlc so that it can run as sudo? As it turns out, this is a necessary step in the pi installations:
> 
> `sed -i 's/geteuid/getppid/' /usr/bin/vlc `

Yes I did.

**Comment by vicwomg** [comment]
Then I am at a loss, hopefully someone with more direct Linux experience can chime in

**Comment by troy-lim** [comment]
> Then I am at a loss, hopefully someone with more direct Linux experience can chime in

Thank you so much for the effort. Hope that someone out there can give some light into this. I'm running out of space in my RasPi-Pikaraoke. :)

**Comment by tbelaire** [comment]
So, I think we might want to be using `cvlc` instead of `vlc`, which avoids it trying to start the interface.

Also if you get the Ascii art display, you need to pass DISPLAY=:0 to force it to not try and draw in the current terminal.

**Comment by troy-lim** [comment]
> So, I think we might want to be using `cvlc` instead of `vlc`, which avoids it trying to start the interface.

I tried using `clvc` but the result is still the same.

> Also if you get the Ascii art display, you need to pass DISPLAY=:0 to force it to not try and draw in the current terminal.

Do you have any idea on how to do this? I tried different methods but I can't seem to get it right.

**Comment by tbelaire** [comment]
I'm using systemd to run on boot

https://github.com/tbelaire/pikaraoke/blob/service/pikaraoke.service#L16

And I added it to the ENV.

But I think you could do something with `os.environ["DISPLAY"] = ":0"` from inside the process.


If running directly, it would be
```shell
DISPLAY=:0 python app.py
```

**Comment by Teamustu** [comment]
> > Have you tried without running `python3 app.py` without sudo?
> 
> ![IMG20220201064326.jpg](https://user-images.githubusercontent.com/73457175/151886657-699c729b-7800-45d6-a469-7c11156c0bc0.jpg)

Hi, I had a similar issue running without sudo, but running with sudo wouldn't load sound. I found that if you just made the user the owner of the qrcode file and run without sudo, it works. I am on ubuntu, and I did chmod sudo chown user qrcode.png then launched without sudo and it worked. Maybe give it a try?

**Comment by vicwomg** [comment]
VLC has been deprecated from Pikaraoke 1.2
