### ISSUE TITLE
Stuck with windows install

### ISSUE THREAD

**Issue by kungfuk** [vicwomg/pikaraoke#193]
I'm trying to do a windows install and am stuck at "Open a powershell, and go to the pikaraoke directory:" "

How do i get to said directory?

**Comment by troy-lim** [comment]
I think you should clone first. 
`git clone https://github.com/vicwomg/pikaraoke.git`

**Comment by kungfuk** [comment]
I dont know what that means

**Comment by kungfuk** [comment]
Okay, now it says Metadata-generation-failed. 

 Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
PS C:\Users\macke\OneDrive\Documents\GitHub\pikaraoke> python3 app.py
Traceback (most recent call last):
  File "C:\Users\macke\OneDrive\Documents\GitHub\pikaraoke\app.py", line 13, in <module>
    import cherrypy
ModuleNotFoundError: No module named 'cherrypy'
PS C:\Users\macke\OneDrive\Documents\GitHub\pikaraoke> python3 app.py
Traceback (most recent call last):
  File "C:\Users\macke\OneDrive\Documents\GitHub\pikaraoke\app.py", line 13, in <module>
    import cherrypy
ModuleNotFoundError: No module named 'cherrypy'
PS C:\Users\macke\OneDrive\Documents\GitHub\pikaraoke> python3 app.py
Traceback (most recent call last):
  File "C:\Users\macke\OneDrive\Documents\GitHub\pikaraoke\app.py", line 13, in <module>
    import cherrypy
ModuleNotFoundError: No module named 'cherrypy'
PS C:\Users\macke\OneDrive\Documents\GitHub\pikaraoke>
PS C:\Users\macke\OneDrive\Documents\GitHub\pikaraoke> pip3 install -r requirements.txt
Ignoring pygame: markers 'sys_platform != "darwin" and sys_platform != "win32"' don't match your environment
Ignoring pygame: markers 'sys_platform == "darwin"' don't match your environment
Collecting tempora==1.14.0
  Using cached tempora-1.14-py2.py3-none-any.whl (13 kB)
Collecting jaraco.functools==2.0
  Using cached jaraco.functools-2.0-py2.py3-none-any.whl (6.7 kB)
Collecting CherryPy==10.2.1
  Using cached CherryPy-10.2.1-py2.py3-none-any.whl (435 kB)
Collecting six==1.12.0
  Using cached six-1.12.0-py2.py3-none-any.whl (10 kB)
Collecting Flask
  Using cached Flask-2.0.3-py3-none-any.whl (95 kB)
Collecting pillow
  Using cached Pillow-9.0.1-cp310-cp310-win_amd64.whl (3.2 MB)
Collecting qrcode
  Using cached qrcode-7.3.1.tar.gz (43 kB)
  Preparing metadata (setup.py) ... done
Collecting pygame==2.0.1
  Using cached pygame-2.0.1.tar.gz (5.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]


      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using WINDOWS configuration...

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\macke\AppData\Local\Temp\pip-install-xjet7n4r\pygame_e7d49c6da69b4d9a955be8af0c7ee6bf\setup.py", line 318, in <module>
          buildconfig.config.main(AUTO_CONFIG)
        File "C:\Users\macke\AppData\Local\Temp\pip-install-xjet7n4r\pygame_e7d49c6da69b4d9a955be8af0c7ee6bf\buildconfig\config.py", line 221, in main
          deps = CFG.main(**kwds)
        File "C:\Users\macke\AppData\Local\Temp\pip-install-xjet7n4r\pygame_e7d49c6da69b4d9a955be8af0c7ee6bf\buildconfig\config_win.py", line 559, in main
          and download_win_prebuilt.ask(**download_kwargs):
        File "C:\Users\macke\AppData\Local\Temp\pip-install-xjet7n4r\pygame_e7d49c6da69b4d9a955be8af0c7ee6bf\buildconfig\download_win_prebuilt.py", line 275, in ask
          update(x86=x86, x64=x64, sdl2=sdl2)
        File "C:\Users\macke\AppData\Local\Temp\pip-install-xjet7n4r\pygame_e7d49c6da69b4d9a955be8af0c7ee6bf\buildconfig\download_win_prebuilt.py", line 258, in update
          download_prebuilts(download_dir, x86=x86, x64=x64, sdl2=sdl2)
        File "C:\Users\macke\AppData\Local\Temp\pip-install-xjet7n4r\pygame_e7d49c6da69b4d9a955be8af0c7ee6bf\buildconfig\download_win_prebuilt.py", line 107, in download_prebuilts
          download_sha1_unzip(url, checksum, temp_dir, 1)
        File "C:\Users\macke\AppData\Local\Temp\pip-install-xjet7n4r\pygame_e7d49c6da69b4d9a955be8af0c7ee6bf\buildconfig\download_win_prebuilt.py", line 40, in download_sha1_unzip
          response = urllib.urlopen(request).read()
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 216, in urlopen
          return opener.open(url, data, timeout)
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 525, in open
          response = meth(req, response)
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 634, in http_response
          response = self.parent.error(
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 557, in error
          result = self._call_chain(*args)
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 496, in _call_chain
          result = func(*args)
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 749, in http_error_302
          return self.parent.open(new, timeout=req.timeout)
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 525, in open
          response = meth(req, response)
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 634, in http_response
          response = self.parent.error(
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 563, in error
          return self._call_chain(*args)
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 496, in _call_chain
          result = func(*args)
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 643, in http_error_default
          raise HTTPError(req.full_url, code, msg, hdrs, fp)
      urllib.error.HTTPError: HTTP Error 502: Bad Gateway
      Making dir :prebuilt_downloads:
      Downloading... https://www.libsdl.org/release/SDL2-devel-2.0.14-VC.zip 48d5dcd4a445410301f5575219cffb6de654edb8
      Unzipping :prebuilt_downloads\SDL2-devel-2.0.14-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip 137f86474691f4e12e76e07d58d5920c8d844d5b
      Unzipping :prebuilt_downloads\SDL2_image-devel-2.0.5-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-VC.zip 1436df41ebc47ac36e02ec9bda5699e80ff9bd27
      Unzipping :prebuilt_downloads\SDL2_ttf-devel-2.0.15-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip 9097148f4529cf19f805ccd007618dec280f0ecc
      Unzipping :prebuilt_downloads\SDL2_mixer-devel-2.0.4-VC.zip:
      Downloading... https://www.ijg.org/files/jpegsr9d.zip ed10aa2b5a0fcfe74f8a6f7611aeb346b06a1f99
      Unzipping :prebuilt_downloads\jpegsr9d.zip:
      Downloading... https://pygame.org/ftp/prebuilt-x64-pygame-1.9.2-20150922.zip 3a5af3427b3aa13a0aaf5c4cb08daaed341613ed

      ---
      For help with compilation see:
          https://www.pygame.org/wiki/CompileWindows
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by xuancong84** [comment]
You should install Anaconda3 (https://www.anaconda.com/products/individual) and use its `pip` to install `requirements.txt`. See my fork (https://github.com/xuancong84/pikaraoke), even the vocal splitter is working with GPU acceleration.
