### ISSUE TITLE
Error when a downloading song is set to be queued after it finishes

### ISSUE THREAD

**Issue by AaronMeyers** [vicwomg/pikaraoke#215]
Whenever I search and download a song with the immediately queue it option selected, when the download finishes, I see this error in the terminal and the song does not get queued. It does show up in the library and it downloads just fine, but the error seems to prevent it from getting queued.

Running on macOS Big Sur. Is there an obvious solution that I'm missing? Is my Python version wrong? Everything else is working great!

```
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/Users/aaron/opt/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/aaron/opt/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/aaron/pikaraoke/karaoke.py", line 463, in download_video
    s = self.find_song_by_youtube_id(y)
  File "/Users/aaron/pikaraoke/karaoke.py", line 517, in find_song_by_youtube_id
    if youtube_id in each:
TypeError: 'in <string>' requires string as left operand, not NoneType
```

**Comment by Hartebee5t** [comment]
I'm no expert but at first guess I would check into the last line-number reference in the traceback (line 517 of .../karaoke.py). The trace list may not have gone back far enough to reach the root cause.
I'd  wonder if there could be a race condition between the new downloaded file being created and line 517 being executed (expecting a valid filename as an argument but not yet populated at execution time). Possibly a difference in the way macOS performs these concurrent actions?

**Comment by Hartebee5t** [comment]
I'm no expert but at first guess I would check into the last line-number reference in the traceback (line 517 of .../karaoke.py). The trace list may not have gone back far enough to reach the root cause.
I'd  wonder if there could be a race condition between the new downloaded file being created and line 517 being executed (expecting a valid filename as an argument but not yet populated at execution time). Possibly a difference in the way macOS performs these concurrent actions?

**Comment by vicwomg** [comment]
Hmm, I can't reproduce this issue on my mac. Looks like you're using anaconda to install the dependencies/python. Have you tried with just pip3?

**Comment by vicwomg** [comment]
That youtube-dl path stuff definitely sounds like the root cause.

If you're pointing it to `/usr/local/bin/youtube-dl ` you might be running an older install of youtube-dl (which is the lesser maintained root branch), and not yt-dlp (now required by pikaraoke). 

Try running:
`/usr/local/bin/yt-dlp --version`

If that returns command not found, you didn't set up the symlink properly. 

Assuming your paths are accurate, you can probably correct that with:
`sudo ln -s /Users/aaron/opt/anaconda3/bin/yt-dlp /usr/local/bin/yt-dlp`

Then try running again (without the --youtube-dl param)

**Comment by AaronMeyers** [comment]
Yea yt-dlp is definitely in that anaconda3 subdir. i used your command to fix the symlink and now i can launch pikaraoke without the youtube-dl argument!

i did a test and the queue after downloading worked! thank you so much for helping me fix this :)

Had a bunch of people over for karaoke this weekend and even with the busted queueing, it was still a huge hit! Can't wait to do it again now that this is sorted out. Thank you!

**Comment by vicwomg** [comment]
Great! glad to hear it was a party hit :)
