### ISSUE TITLE
[BUG] RaspberryPi 4 - Getting selenium error on ./pikaraoke.sh execution

### ISSUE THREAD

**Issue by Altheran88** [vicwomg/pikaraoke#313]
Fresh Pi 4 installation, I went with the full 64 bit installation to be sure.

Here are the exact steps I took logged-in via SSH under the user "pi" on first boot :

sudo apt update && sudo apt upgrade -y
reboot
git clone https://github.com/vicwomg/pikaraoke.git
cd pikaraoke
./setup.sh
./pikaraoke.sh

Here is what I am getting from the .sh execution

-----------------------------------------------------

pi@pikaraoke:~/pikaraoke $ ./pikaraoke.sh
[2024-01-05 16:33:29] INFO: Fetching available songs in: /home/pi/pikaraoke-songs/
[05/Jan/2024:16:33:29] ENGINE Bus STARTING
[2024-01-05 16:33:29] INFO: [05/Jan/2024:16:33:29] ENGINE Bus STARTING
[05/Jan/2024:16:33:30] ENGINE Serving on http://0.0.0.0:5555
[2024-01-05 16:33:30] INFO: [05/Jan/2024:16:33:30] ENGINE Serving on http://0.0.0.0:5555
[05/Jan/2024:16:33:30] ENGINE Bus STARTED
[2024-01-05 16:33:30] INFO: [05/Jan/2024:16:33:30] ENGINE Bus STARTED
Traceback (most recent call last):
  File "/home/pi/pikaraoke/app.py", line 863, in <module>
    driver = webdriver.Chrome(service=service, options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/pikaraoke/.venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/pi/pikaraoke/.venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 61, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/pi/pikaraoke/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 209, in __init__
    self.start_session(capabilities)
  File "/home/pi/pikaraoke/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 293, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/pikaraoke/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "/home/pi/pikaraoke/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x00556bbb75f4 <unknown>
#1 0x00556b8a7264 <unknown>
#2 0x00556b8d9304 <unknown>
#3 0x00556b8d57cc <unknown>
#4 0x00556b91badc <unknown>
#5 0x00556b8e0a2c <unknown>
#6 0x00556b8e1c44 <unknown>
#7 0x00556bb8160c <unknown>
#8 0x00556bb849c0 <unknown>
#9 0x00556bb71aec <unknown>
#10 0x00556bb8537c <unknown>
#11 0x00556bb59ea0 <unknown>
#12 0x00556bba53f0 <unknown>
#13 0x00556bba55bc <unknown>
#14 0x00556bbb67a8 <unknown>
#15 0x007fae34ee18 <unknown>
#16 0x007fae3b7e9c <unknown>

-----------------------------------------------------

Then I can CTRL+C to end the execution

-----------------------------------------------------

^CException ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1583, in _shutdown
    lock.acquire()
KeyboardInterrupt:
/home/pi/pikaraoke/.venv/lib/python3.11/site-packages/cherrypy/process/wspbus.py:254: RuntimeWarning: The main thread is exiting, but the Bus is in the states.STARTED state; shutting it down automatically now. You must either call bus.block() after start(), or call bus.exit() before the main thread exits.
  warnings.warn(
[05/Jan/2024:16:40:07] ENGINE Bus STOPPING
[2024-01-05 16:40:07] INFO: [05/Jan/2024:16:40:07] ENGINE Bus STOPPING
[05/Jan/2024:16:40:07] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 5555)) shut down
[2024-01-05 16:40:07] INFO: [05/Jan/2024:16:40:07] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 5555)) shut down
[05/Jan/2024:16:40:07] ENGINE Bus STOPPED
[2024-01-05 16:40:07] INFO: [05/Jan/2024:16:40:07] ENGINE Bus STOPPED
[05/Jan/2024:16:40:07] ENGINE Bus EXITING
[2024-01-05 16:40:07] INFO: [05/Jan/2024:16:40:07] ENGINE Bus EXITING
[05/Jan/2024:16:40:07] ENGINE Bus EXITED
[2024-01-05 16:40:07] INFO: [05/Jan/2024:16:40:07] ENGINE Bus EXITED

**Comment by vicwomg** [comment]
You probably can’t run over SSH unless you run with the —headless option.
Reason being by default PiKaraoke will try to launch a browser with the
splash screen UI

**Comment by Altheran88** [comment]
That's it, Ive configured the autostart and at reboot, it all worked, thanks !
