### ISSUE TITLE
[BUG] Debian/LinuxLite fails to launch pikaraoke: "no chrome binary at /usr/bin/google-chrome"

### ISSUE THREAD

**Issue by TekyTech** [vicwomg/pikaraoke#339]
**Crashes upon start.**

- Installed fresh LinuxLite 7.0 (based on Ubuntu 24.04) on an intel-based desktop
- Installed all LinuxLite updates
- Installed pikaraoke 
- The installer does not recognize that it is a Debian distro and did not install everything, but it is ok, can install whatever is missing manually.
- Manually installed python venv, chromium, chromium driver, ffmpeg
- ./setup.sh - installation finished without warnings after all the above is installed.

**When starting ./pikaraoke.sh it shows errors:**

./pikaraoke.sh
/home/user/pikaraoke/app.py:650: SyntaxWarning: invalid escape sequence '\S'
  return os.path.join(os.path.dirname(__file__), ".venv\Scripts\yt-dlp.exe")
/home/user/pikaraoke/app.py:658: SyntaxWarning: invalid escape sequence '\p'
  legacy_directory = os.path.expanduser("~\pikaraoke\songs")
/home/user/pikaraoke/app.py:662: SyntaxWarning: invalid escape sequence '\p'
  return "~\pikaraoke-songs"
[2024-06-23 06:48:32] INFO: Fetching available songs in: /home/user/pikaraoke-songs/
[23/Jun/2024:06:48:33] ENGINE Bus STARTING
[2024-06-23 06:48:33] INFO: [23/Jun/2024:06:48:33] ENGINE Bus STARTING
[23/Jun/2024:06:48:33] ENGINE Serving on http://0.0.0.0:5555
[2024-06-23 06:48:33] INFO: [23/Jun/2024:06:48:33] ENGINE Serving on http://0.0.0.0:5555
[23/Jun/2024:06:48:33] ENGINE Bus STARTED
[2024-06-23 06:48:33] INFO: [23/Jun/2024:06:48:33] ENGINE Bus STARTED
Traceback (most recent call last):
  File "/home/user/pikaraoke/app.py", line 899, in <module>
    driver = webdriver.Chrome(service=service, options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/pikaraoke/.venv/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/user/pikaraoke/.venv/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/user/pikaraoke/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/home/user/pikaraoke/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/pikaraoke/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/user/pikaraoke/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from unknown error: no chrome binary at /usr/bin/google-chrome
Stacktrace:
#0 0x59cf2d0fbc4a <unknown>
#1 0x59cf2cdf629c <unknown>
#2 0x59cf2ce28a77 <unknown>
#3 0x59cf2ce26ea6 <unknown>
#4 0x59cf2ce70db8 <unknown>
#5 0x59cf2ce646e3 <unknown>
#6 0x59cf2ce34879 <unknown>
#7 0x59cf2ce351ce <unknown>
#8 0x59cf2d0c496f <unknown>
#9 0x59cf2d0c8af6 <unknown>
#10 0x59cf2d0b179c <unknown>
#11 0x59cf2d0c9291 <unknown>
#12 0x59cf2d0976ce <unknown>
#13 0x59cf2d0eb0d8 <unknown>
#14 0x59cf2d0eb2e6 <unknown>
#15 0x59cf2d0facfd <unknown>
#16 0x7a0e965c4ac3 <unknown>

**Comment by TekyTech** [comment]
UPDATE:
I've found a fix here:
https://stackoverflow.com/questions/62233719/webdriverexception-no-chrome-binary-at-usr-bin-google-chrome-stable-or-chrome

The solution to simply uninstall chromium worked for me

**Comment by vicwomg** [comment]
updated the issue title to be more specific

**Comment by vicwomg** [comment]
Closing as I don't think this is a pikaraoke bug. We also deprecated the setup script so you are on your own for figuring out how to install dependencies like chrome and ffmpeg
