### ISSUE TITLE
[BUG] Not starting on rpi 400 latest raspberry pi OS

### ISSUE THREAD

**Issue by monteslu** [vicwomg/pikaraoke#347]
**Describe the bug**

Error running on rpi 400 latest raspberry pi OS fully updated

```
pi@rp400:~/pikaraoke $ ./pikaraoke.sh
Traceback (most recent call last):
  File "/home/pi/pikaraoke/app.py", line 20, in <module>
    from selenium import webdriver
  File "/home/pi/pikaraoke/.venv/lib/python3.11/site-packages/selenium/webdriver/__init__.py", line 20, in <module>
    from .chrome.webdriver import WebDriver as Chrome  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/pikaraoke/.venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 18, in <module>
    from selenium.webdriver.chromium.webdriver import ChromiumDriver
  File "/home/pi/pikaraoke/.venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 22, in <module>
    from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
  File "/home/pi/pikaraoke/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 67, in <module>
    from .websocket_connection import WebSocketConnection
  File "/home/pi/pikaraoke/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/websocket_connection.py", line 23, in <module>
    from websocket import WebSocketApp
ModuleNotFoundError: No module named 'websocket'

```

**To Reproduce**
1. Install latest rasperry pi OS
2. run setup
3. launch

**Expected behavior**
Should load server and fire up browser

**Screenshots**

**Platform (please complete the following information):**
 - pi 400
 - OS: Raspberry Pi OS
 - OS version: Bookworm
 - Browser Chromium
 - Version pikaraoke master branch

**Additional context**

Perhaps there can be an option to start headless and we can just fire up the browser ourselves?

**Comment by q2000drum** [comment]
Hello Luis, I followed the same process on a PI 4B and got the same results.
Any help from the developer would be appreciated.

**Comment by monteslu** [comment]
temporary workaround until this gets fixed
in `app.py` comment out:
```python
# from selenium import webdriver
# from selenium.webdriver.chrome.options import Options
# from selenium.webdriver.chrome.service import Service
# from selenium.webdriver.common.by import By
# from selenium.webdriver.common.keys import Keys
# from selenium.webdriver.support import expected_conditions as EC
# from selenium.webdriver.support.ui import WebDriverWait
```

and this:
```python
    # if not args.hide_splash_screen: 
    #     if platform == "raspberry_pi":
    #         service = Service(executable_path='/usr/bin/chromedriver')
    #     else: 
    #         service = None
    #     options = Options()

    #     if args.window_size:
    #         options.add_argument("--window-size=%s" % (args.window_size))
    #         options.add_argument("--window-position=0,0")
            
    #     options.add_argument("--kiosk")
    #     options.add_argument("--start-maximized")
    #     options.add_experimental_option("excludeSwitches", ['enable-automation'])
    #     driver = webdriver.Chrome(service=service, options=options)
    #     driver.get(f"{k.url}/splash" )
    #     driver.add_cookie({'name': 'user', 'value': 'PiKaraoke-Host'})
    #     # Clicking this counts as an interaction, which will allow the browser to autoplay audio
    #     wait = WebDriverWait(driver, 60)
    #     elem = wait.until(EC.element_to_be_clickable((By.ID, "permissions-button")))
    #     elem.click()
```

It will let you launch the server, then you can open the browser to the URL it shows you on the command line.

**Comment by vicwomg** [comment]
This was fixed a couple of days ago. It's a selenium release incompatibility. A `git pull` and rerun of `./setup.sh` of the latest master branch should address the issue.

To check, ensure requirements.txt contains `selenium==4.21.0` if not, you need to pull the update and rerun setup

**Comment by vicwomg** [comment]
> Perhaps there can be an option to start headless and we can just fire up the browser ourselves?

There is: `./pikaraoke.sh --headless`

See `./pikaraoke.sh --help` for all options

**Comment by vicwomg** [comment]
dup of #346
