### ISSUE TITLE
Websocket not Found

### ISSUE THREAD

**Issue by Lynwood** [vicwomg/pikaraoke#349]
### Discussed in https://github.com/vicwomg/pikaraoke/discussions/346

<div type='discussions-op-text'>

<sup>Originally posted by **Ivampsman** July 11, 2024</sup>
Hi,

I've installed as described in my Raspberry Pi 4, running the last release of Raspbian 64bit, but I've received a error message when running it. showed bellow:

~/pikaraoke $ ./pikaraoke.sh
Traceback (most recent call last):
  File "/home/ivamps/pikaraoke/app.py", line 20, in <module>
    from selenium import webdriver
  File "/home/ivamps/pikaraoke/.venv/lib/python3.11/site-packages/selenium/webdriver/__init__.py", line 20, in <module>
    from .chrome.webdriver import WebDriver as Chrome  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivamps/pikaraoke/.venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 18, in <module>
    from selenium.webdriver.chromium.webdriver import ChromiumDriver
  File "/home/ivamps/pikaraoke/.venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 22, in <module>
    from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
  File "/home/ivamps/pikaraoke/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 67, in <module>
    from .websocket_connection import WebSocketConnection
  File "/home/ivamps/pikaraoke/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/websocket_connection.py", line 23, in <module>
    from websocket import WebSocketApp
ModuleNotFoundError: No module named 'websocket'

Is anything I have missed?
</div>

I'm so happy to find this discussion..lol..all the reddit chat was fromj years ago...a few new ones from 7 months ago.

I am getting the same error, and I tried a GIT PULL, but it tells me "fatal: not a git repository (or any of the parent directories:: .git

Is this because the folder name is pikaraoke-1.2?  I couldnt remember how to use mv to rename the folder...been too long ago I guess..

any help is appreciated...this program is awesome (I installed from an older image at first, but wanted a newer version so I installed a fresh copy of Raspian, and downloaded the source and compiled)

Lynwood

**Comment by vicwomg** [comment]
Please move this to discussion
