### ISSUE TITLE
How to change download path? 

### ISSUE THREAD

**Issue by Rluke88** [vicwomg/pikaraoke#370]
I can see the default path assigned to ~/pikaraoke-songs, but how do I change that? I want to have that default to a folder on my external HD.

**Comment by vicwomg** [comment]
https://github.com/vicwomg/pikaraoke/discussions/352

**Comment by Rluke88** [comment]
I ran than, but I received the below errors.  Any tips?

``:~/pikaraoke $ ./pikaraoke.sh -d /media/rluke/SP PHD U3/Karaoke
[2024-08-19 15:11:15] INFO: Fetching available songs in: /media/rluke/SP PHD U3/Karaoke/
[19/Aug/2024:15:11:16] ENGINE Bus STARTING
[2024-08-19 15:11:16] INFO: [19/Aug/2024:15:11:16] ENGINE Bus STARTING
[19/Aug/2024:15:11:17] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7fff16fdf2d0>>
Traceback (most recent call last):
  File "/home/rluke/pikaraoke/.venv/lib/python3.11/site-packages/portend.py", line 122, in free
    Checker(timeout=0.1).assert_free(host, port)
  File "/home/rluke/pikaraoke/.venv/lib/python3.11/site-packages/portend.py", line 71, in assert_free
    list(itertools.starmap(self._connect, info))
  File "/home/rluke/pikaraoke/.venv/lib/python3.11/site-packages/portend.py", line 87, in _connect
    raise PortNotFree(tmpl.format(**locals()))
portend.PortNotFree: Port 5555 is in use on 0.0.0.0.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rluke/pikaraoke/.venv/lib/python3.11/site-packages/cherrypy/process/wspbus.py", line 229, in publish
    output.append(listener(*args, **kwargs))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rluke/pikaraoke/.venv/lib/python3.11/site-packages/cherrypy/_cpserver.py", line 191, in start
    super(Server, self).start()
  File "/home/rluke/pikaraoke/.venv/lib/python3.11/site-packages/cherrypy/process/servers.py", line 176, in start
    portend.free(*self.bind_addr, timeout=Timeouts.free)
  File "/home/rluke/pikaraoke/.venv/lib/python3.11/site-packages/portend.py", line 126, in free
    raise Timeout("Port {port} not free on {host}.".format(**locals()))
portend.Timeout: Port 5555 not free on 0.0.0.0.

[2024-08-19 15:11:17] ERROR: [19/Aug/2024:15:11:17] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7fff16fdf2d0>>
Traceback (most recent call last):
  File "/home/rluke/pikaraoke/.venv/lib/python3.11/site-packages/portend.py", line 122, in free
    Checker(timeout=0.1).assert_free(host, port)
  File "/home/rluke/pikaraoke/.venv/lib/python3.11/site-packages/portend.py", line 71, in assert_free
    list(itertools.starmap(self._connect, info))
  File "/home/rluke/pikaraoke/.venv/lib/python3.11/site-packages/portend.py", line 87, in _connect
    raise PortNotFree(tmpl.format(**locals()))
portend.PortNotFree: Port 5555 is in use on 0.0.0.0.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rluke/pikaraoke/.venv/lib/python3.11/site-packages/cherrypy/process/wspbus.py", line 229, in publish
    output.append(listener(*args, **kwargs))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rluke/pikaraoke/.venv/lib/python3.11/site-packages/cherrypy/_cpserver.py", line 191, in start
    super(Server, self).start()
  File "/home/rluke/pikaraoke/.venv/lib/python3.11/site-packages/cherrypy/process/servers.py", line 176, in start
    portend.free(*self.bind_addr, timeout=Timeouts.free)
  File "/home/rluke/pikaraoke/.venv/lib/python3.11/site-packages/portend.py", line 126, in free
    raise Timeout("Port {port} not free on {host}.".format(**locals()))
portend.Timeout: Port 5555 not free on 0.0.0.0.

[19/Aug/2024:15:11:17] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/home/rluke/pikaraoke/.venv/lib/python3.11/site-packages/cherrypy/process/wspbus.py", line 267, in start
    self.publish('start')
  File "/home/rluke/pikaraoke/.venv/lib/python3.11/site-packages/cherrypy/process/wspbus.py", line 247, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: Timeout('Port 5555 not free on 0.0.0.0.')

[2024-08-19 15:11:17] ERROR: [19/Aug/2024:15:11:17] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/home/rluke/pikaraoke/.venv/lib/python3.11/site-packages/cherrypy/process/wspbus.py", line 267, in start
    self.publish('start')
  File "/home/rluke/pikaraoke/.venv/lib/python3.11/site-packages/cherrypy/process/wspbus.py", line 247, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: Timeout('Port 5555 not free on 0.0.0.0.')

[19/Aug/2024:15:11:17] ENGINE Bus STOPPING
[2024-08-19 15:11:17] INFO: [19/Aug/2024:15:11:17] ENGINE Bus STOPPING
[19/Aug/2024:15:11:17] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 5555)) already shut down
[2024-08-19 15:11:17] INFO: [19/Aug/2024:15:11:17] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 5555)) already shut down
[19/Aug/2024:15:11:17] ENGINE Bus STOPPED
[2024-08-19 15:11:17] INFO: [19/Aug/2024:15:11:17] ENGINE Bus STOPPED
[19/Aug/2024:15:11:17] ENGINE Bus EXITING
[2024-08-19 15:11:17] INFO: [19/Aug/2024:15:11:17] ENGINE Bus EXITING
[19/Aug/2024:15:11:17] ENGINE Bus EXITED
[2024-08-19 15:11:17] INFO: [19/Aug/2024:15:11:17] ENGINE Bus EXITED

**Comment by vicwomg** [comment]
The error indicates something else is occupying port 5555. You may already have pikaraoke running. Restart your pi and try again.

**Comment by Rluke88** [comment]
That worked for putting new downloads in the right place, but those downloads are not showing up under Browse in the program when I relaunch PiKaraoke. It knows where to assign the downloads but not where to look to grab and play them. Any ideas?

**Comment by vicwomg** [comment]
Your download path includes spaces. You may need to escape those with backslashes: `./pikaraoke.sh -d /media/rluke/SP\ PHD\ U3/Karaoke`

Otherwise I'd need to see the logs, preferably with debug output (add the `-l10` param to your launch command), to know.

**Comment by Rluke88** [comment]
So, any settings I change keep reverting back to the program's defaults.  Any tips on how to get them to stick?  

Any time I make a change in the terminal to setting, it only applies to that session and then reverts  back to the defaults on the next launch.  I went into Karaoke.py to make the below updates and save, but the old settings still show up when running the -l10 command. 
"> def __init__(
        self,
        port=5555,
        ffmpeg_port=5556,
        download_path="/media/rluke/SP PHD U312",
        hide_url=False,
        hide_raspiwifi_instructions=False,
        hide_splash_screen=False,
        high_quality=True,
        volume=1.00,"

When running -l10 
"^[[Arluke@raspberrypi:~/pikaraoke $ ./pikaraoke.sh -l10
[2024-08-26 15:11:06] DEBUG: 
    http port: 5555
    ffmpeg port 5556
    hide URL: False
    prefer hostname: False
    url override: None
    hide RaspiWiFi instructions: False
    headless (hide splash): False
    splash_delay: 3
    screensaver_timeout: 300
    high quality video: False
    download path: /home/rluke/pikaraoke-songs/
    default volume: 0.85
    youtube-dl path: /home/rluke/pikaraoke/.venv/bin/yt-dlp
    logo path: /home/rluke/pikaraoke/logo.png
    log_level: 10
    hide overlay: False"

**Comment by vicwomg** [comment]
This is not how you set the defaults.

You probably shouldn’t be editing the project source code unless you know
what you’re doing. The proper way to set your defaults is at run time
./pikaraoke.sh -d (download path)

**Comment by vicwomg** [comment]
> Any time I make a change in the terminal to setting, it only applies to that session and then reverts back to the defaults on the next launch. 

You may need to explain this. How are you starting on your "next launch"? 

If you've configured auto start in `/etc/rc.local` you simply need to add the `-d <your_download_path>` to the command there to pick up your runtime download directory. If you're launching it manually, you will need to always specify the -d option, or make an linux alias to do so if you want to make it easier to remember.

**Comment by Rluke88** [comment]
Launching manually. I didn’t realize you had to run the change the defaults at every launch. I created a desktop shortcut and included my changes in the execute script. That did what I needed without having to manually enter those preferences every time. I appreciate your help. I’m obviously new at this.
