### ISSUE TITLE
Exceptions thrown on start up if browser window open to /nowplaying

### ISSUE THREAD

**Issue by vicwomg** [vicwomg/pikaraoke#58]
If there is an active browser trying to fetch from /nowplaying (probably from a previous karaoke session) the app will throw exceptions during start up. Best to catch and handle them.

```[2020-11-01 16:57:10] ERROR: Exception on /nowplaying [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 66, in nowplaying
    if len(k.queue) >= 1:
NameError: name 'k' is not defined```

**Comment by vicwomg** [comment]
Will now show this:

```
[2020-12-26 21:39:16] DEBUG: Generating URL QR code
[2020-12-26 21:39:16] DEBUG: Initializing pygame
[2020-12-26 21:39:17] ERROR: Problem loading /nowplaying, pikaraoke may still be starting up: global name 'k' is not defined
[2020-12-26 21:39:19] ERROR: Problem loading /nowplaying, pikaraoke may still be starting up: global name 'k' is not defined
[2020-12-26 21:39:20] DEBUG: Initializing screen mode
[2020-12-26 21:39:20] DEBUG: Done initializing splash screen
[2020-12-26 21:39:20] DEBUG: Rendering splash screen
```
